image:
  file: .gitpodcontainer/Dockerfile

tasks:
  - name: App Process
    init: gradle clean build -x test
    command: java -jar target/*.jar
  - env:
      name: YB_VERSION
      value: 2.7.1.1
  - env:
      name: YB_VERSION
      value: 2.7.1.1
  - env:
      name: ROLE
      value: gitpod

# exposed ports
ports:
  - port: 8080
    onOpen: open-preview
  - port: 7000
    onOpen: open-preview
  - port: 9000
    onOpen: open-preview

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
    - GitHub.vscode-pull-request-github