apiVersion: skaffold/v2beta12
kind: Config
build:
  artifacts:
    - image: humourmind/todo
      context: ../
      buildpacks:
        builder: paketobuildpacks/builder:base
  tagPolicy:
    envTemplate:
      template: '1.0'
  local:
    push: true
deploy:
  kustomize: {}
